service: ci-vcs-hook-cb

custom:
  project_svc_url: "https://github.com/SteveHoggNZ/my-micro.git"
  project_stage: ${file(../../project.yml):name}-${self:provider.stage}

plugins:
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: prod
  stackTags:
    PROJECT: ${file(../../project.yml):name}
  region: ap-southeast-2
  tracing: true

  environment:
    CODE_BUILD_PROJECT: ${cf:${self:custom.project_stage}.CodeBuildExtract}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "codebuild:StartBuild"
      Resource:
        - "*"

# package:
#   exclude:
#     - src/api/git-2.4.3.tar

functions:
  notify:
    handler: src/api/handler.notify
    events:
     - http:
         path: notify
         method: post

resources:
  Resources:
