version: 0.2

phases:
  install:
    commands:
      - npm i
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - SVC=$(node -p "require('./package.json').name")
      - echo Build for ${SVC} started on `date`
      - npm run build
      - mkdir -p package
      - mv .serverless package/${SVC}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package/**/*
  discard-paths: no
