version: 0.2

phases:
  install:
    commands:
      # install dev dependencies so they don't get packaged by Serverless
      - npm install --only=dev
      - mv node_modules node_modules_dev
      - export NODE_PATH=$NODE_PATH:$PWD/node_modules_dev
      - export PATH=$PATH:$PWD/node_modules_dev/.bin
      # install production dependencies
      - npm install --only=production
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - SVC=$(node -p "require('./package.json').name")
      - echo ${BUILD_ACTION} for ${SVC} started on `date`
      - if [[ $BUILD_ACTION == Build ]]; then npm run build; fi
      - if [[ $BUILD_ACTION == Deploy ]]; then npm run deploy; fi
  post_build:
    commands:
      # node_modules are only required during build phase
      - rm -fr node_modules
      - rm -fr node_modules_dev
      - ls -al
      - cat /codebuild/output/tmp/script.sh
      - echo ${BUILD_ACTION} for ${SVC} completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
