service: cd-deploy

custom:
  project: my-micro
  project_stage: ${self:custom.project}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3
  stage: prod
  stackTags:
    PROJECT: ${self:custom.project}
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "codepipeline:PutJobSuccessResult"
      Resource:
        - "*"

package:
  exclude:
  - node_modules_dev/**

functions:
  deploy:
    handler: handler.deploy

resources:
  Resources:
    # Creating a pipeline in the console then describing it is the easiest option
    # to see what needs to be defined i.e.
    # aws codepipeline get-pipeline --name <name>
    CodePipeline:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        Name: ${self:custom.project_stage}-${self:service}
        ArtifactStore:
          Type: S3
          Location: codepipeline-ap-southeast-2-285005911711
        # To Do, use globally defined infrastructure role
        RoleArn: arn:aws:iam::798269391015:role/AWS-CodePipeline-Service
        Stages:
          - Name: Source
            Actions:
              - Name: Source
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: '1'
                Configuration:
                  S3Bucket: ${cf:${self:custom.project_stage}.S3Src}
                  # To Do, set the location of the zip as a variable above
                  S3ObjectKey: "build/queue/cd-deploy.zip"
                OutputArtifacts:
                  - Name: ServiceSource
          - Name: Build
            Actions:
              - Name: Build
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: '1'
                InputArtifacts:
                  - Name: ServiceSource
                OutputArtifacts:
                  - Name: ServiceBuild
                Configuration:
                  ProjectName: my-micro-prod-build
                RunOrder: '1'
          - Name: Deploy
            Actions:
              - Name: Log
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: '1'
                InputArtifacts:
                  - Name: ServiceBuild
                OutputArtifacts:
                  - Name: ServiceDeploy
                Configuration:
                  ProjectName: my-micro-prod-deploy
                RunOrder: '1'
  Outputs:
    CodePipeline:
      Description: "Code Pipeline for the project"
      Value:
        { Ref: "CodePipeline" }
