# Prefixing the service with the project name means permissions for the
# deployment resources can be locked down to project* e.g. S3 buckets etc.
service: ${self:custom.project}-cd-deploy

# To Do: don't have a deployment bucket per service!!!

custom:
  # The project.yml file will be in the local directory when using
  # Continuous Deployment, otherwise it is in the project directory
  project: ${file(./project.yml):name, file(../../project.yml):name}
  # Define project_stage for accessing shared infrastructure cf stack
  # i.e. project-prod is a stack, project-dev is a stack etc
  project_stage: ${self:custom.project}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3
  stage: prod
  stackTags:
    PROJECT: ${self:custom.project}
  region: ap-southeast-2
  deploymentBucket: ${cf:${self:custom.project_stage}.S3Src}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "codepipeline:PutJobSuccessResult"
      Resource:
        - "*"

package:
  exclude:
  # Dev dependencies are installed here by buildspec.yml
  - node_modules_dev/**

functions:
  # deploy:
  #   handler: handler.deploy
  sup:
    handler: handler.sup

resources:
  Resources:
    # Creating a pipeline in the console then describing it is the easiest option
    # to see what needs to be defined i.e.
    # aws codepipeline get-pipeline --name <name>
    CodePipeline:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        Name: ${self:service}-${self:provider.stage}
        ArtifactStore:
          Type: S3
          Location: codepipeline-ap-southeast-2-285005911711
        # To Do, use globally defined infrastructure role
        RoleArn: arn:aws:iam::798269391015:role/AWS-CodePipeline-Service
        Stages:
          - Name: Source
            Actions:
              - Name: Source
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: '1'
                Configuration:
                  S3Bucket: ${cf:${self:custom.project_stage}.S3Src}
                  # To Do, set the location of the zip as a variable above
                  S3ObjectKey: "build/queue/cd-deploy.zip"
                OutputArtifacts:
                  - Name: ServiceSource
          - Name: Build
            Actions:
              - Name: Build
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: '1'
                InputArtifacts:
                  - Name: ServiceSource
                OutputArtifacts:
                  - Name: ServiceBuild
                Configuration:
                  ProjectName: my-micro-prod-build
                RunOrder: '1'
          - Name: Deploy
            Actions:
              - Name: Deploy
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: '1'
                InputArtifacts:
                  - Name: ServiceBuild
                OutputArtifacts:
                  - Name: ServiceDeploy
                Configuration:
                  ProjectName: my-micro-prod-deploy
                RunOrder: '1'
  Outputs:
    CodePipeline:
      Description: "Code Pipeline for the project"
      Value:
        { Ref: "CodePipeline" }
