# To Do, tag resources with project name
Parameters:
  ProjectName:
    Type: String
    Default: my-micro
  ProjectSvcUrl:
    Type: String
    Default: https://github.com/SteveHoggNZ/my-micro.git
    Description: Enter the URL for the project version control
  EnvironmentParameter:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Enter dev or prod for environment
Resources:
  S3Src:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          # The default policy CodePipeline generates. It appears very liberal!
          PolicyName: CodePipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - "arn:aws:s3:::codepipeline*"
                  - "arn:aws:s3:::elasticbeanstalk*"
              -
                Effect: Allow
                Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                  - iam:PassRole
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - opsworks:CreateDeployment
                  - opsworks:DescribeApps
                  - opsworks:DescribeCommands
                  - opsworks:DescribeDeployments
                  - opsworks:DescribeInstances
                  - opsworks:DescribeStacks
                  - opsworks:UpdateApp
                  - opsworks:UpdateStack
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - iam:PassRole
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - "*"
  CodeBuildExtract:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - "extract"
      ServiceRole: { "Ref": "CodeBuildRole" }
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/nodejs:7.0.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          -
            Name: BUILD_ACTION
            Value: extract
      Source:
        Type: "GITHUB"
        Location:
          Ref: ProjectSvcUrl
        BuildSpec: "version: 0.1\n\nphases:\n  build:\n    commands:\n      - bash -x scripts/ci-extract-to-s3.sh\n\nartifacts:\n  files:\n    - queue/**/*\n"
      Artifacts:
        Type: "S3"
        Location:
          Ref: S3Src
        Name: "build"
      TimeoutInMinutes: 5
  CodeBuildBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - "build"
      ServiceRole: { "Ref": "CodeBuildRole" }
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/nodejs:7.0.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          -
            Name: BUILD_ACTION
            Value: build
      Source:
        Type: "GITHUB"
        Location:
          Ref: ProjectSvcUrl
      Artifacts:
        Type: "S3"
        Location:
          Ref: S3Src
        Name: "build"
      TimeoutInMinutes: 5
  CodeBuildDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - "deploy"
      ServiceRole: { "Ref": "CodeBuildRole" }
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/nodejs:7.0.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          -
            Name: BUILD_ACTION
            Value: deploy
      Source:
        Type: "GITHUB"
        Location:
          Ref: ProjectSvcUrl
      Artifacts:
        Type: "S3"
        Location:
          Ref: S3Src
        Name: "build"
      TimeoutInMinutes: 5
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
          - # Allow users in the same account to assume the role for debugging
            Effect: Allow
            Principal:
              AWS:
                - Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: "AWS::AccountId"
                    - ":root"
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - "arn:aws:s3:::codepipeline-ap-southeast-2-*"
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:logs:ap-southeast-2:"
                      - Ref: "AWS::AccountId"
                      - ":log-group:/aws/codebuild/*"
                  - Fn::Join:
                    - ""
                    - - "arn:aws:logs:ap-southeast-2:"
                      - Ref: "AWS::AccountId"
                      - ":log-group:/aws/codebuild/*:*"
        -
          PolicyName: ServerlessDeployPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - cloudformation:DescribeStackResources
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DeleteStack
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:cloudformation:*:*:stack/"
                      - Ref: ProjectName
                      - "-*"
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:ListAllMyBuckets
                  - s3:GetBucketVersioning
                  - s3:PutBucketVersioning
                  - s3:GetBucketLocation
                  - s3:PutBucketPolicy
                  - s3:GetBucketWebsite
                  - s3:PutBucketWebsite
                  - s3:DeleteBucketWebsite
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: ProjectName
                      - "-*-serverlessdeployment*"
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: S3Src
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: S3Src
                      - "/*"
              -
                Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:UpdateFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:CreateAlias
                  - lambda:DeleteAlias
                  - lambda:UpdateAlias
                  - lambda:GetFunctionConfiguration
                  - lambda:ListTags
                  - lambda:TagResource
                  - lambda:UntagResource
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:lambda:*:*:function:"
                      - Ref: ProjectName
                      - "-*"
              # To Do: restrict access further
              -
                Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:HEAD
                  - apigateway:OPTIONS
                  - apigateway:PATCH
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                Resource:
                  - "arn:aws:apigateway:*::/restapis"
                  - "arn:aws:apigateway:*::/restapis/*"
              -
                Effect: Allow
                Action:
                  - logs:Describe*
                Resource:
                  - "*"
              # End To Do: restrict access further
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DeleteLogGroup
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:logs::"
                      - Ref: "AWS::AccountId"
                      - ":log-group:/aws/lambda/"
                      - Ref: ProjectName
                      - "-*:*"
              -
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:iam::"
                      - Ref: "AWS::AccountId"
                      - ":role/"
                      - Ref: ProjectName
                      - "-*-lambdaRole"
        -
          PolicyName: ServerlessPipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - codepipeline:UpdatePipeline
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:codepipeline:ap-southeast-2:"
                      - Ref: "AWS::AccountId"
                      - ":"
                      - Ref: ProjectName
                      - "*"
                  # - Fn::Join:
                  #   - ""
                  #   - - "arn:aws:codepipeline::"
                  #     - Ref: "AWS::AccountId"
                  #     - ":"
                  #     - Ref: ProjectName
                  #     - "*"
              -
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt CodePipelineRole.Arn
Outputs:
  S3Src:
    Description: A queue for storing source code to be built
    Value:
      Ref: S3Src
  CodeBuildExtract:
    Description: A service to extract code from version control to be built
    Value:
      Ref: CodeBuildExtract
