service: ${self:custom.project}-${self:custom.name}

custom:
  project: ${file(./project/config.yml):name,
              file(../../project/config.yml):name}
  name: ${file(./package.json):name}
  version: ${file(./package.json):version}
  pipeline: ${file(./project/pipelines/blue-green-release.yml):CodePipeline,
              file(../../project/pipelines/blue-green-release.yml):CodePipeline}
  project_stage: ${self:custom.project}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3
  stage: prod
  stackTags:
    PROJECT: ${self:custom.project}
  region: ap-southeast-2
  deploymentBucket: ${cf:${self:custom.project_stage}.S3Src}
  environment:
    SVC_PROJECT: ${self:custom.project}
    SVC_NAME: ${self:custom.name}
    SVC_VERSION: ${self:custom.version}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - codepipeline:PutJobSuccessResult
        - codepipeline:putJobFailureResult
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - lambda:ListFunctions
      Resource:
        - "*"

package:
  exclude:
  - node_modules_dev/**

functions:
  prerelease:
    handler: src/api/handler.prerelease
  release:
    handler: src/api/handler.release

resources:
  Resources:
    CodePipeline: ${self:custom.pipeline}
  Outputs:
    CodePipeline:
      Description: "Code Pipeline for the project"
      Value:
        { Ref: "CodePipeline" }
